version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_exporter
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./db_exporter
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8041:8080" # Tu backend corre en 8080 dentro del contenedor
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_exporter
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
    restart: always

  frontend:
    build: ./Frontend
    container_name: frontend-app
  
    ports:
      - "8042:80"    # Host 8042 mapea al 80 del contenedor
    restart: always

volumes:
  mysql_data:
